[phases.setup]
nixPkgs = ["chromium", "nss", "freetype", "freetype-dev"]

[phases.install]
cmds = ["npm ci"]

[start]
cmd = "node bot.js"

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/nix/store/x205pbkd5xh5g4iv0g58xjla55has3cx-chromium-108.0.5359.94/bin/chromium"
